/**
 * Mapeamento de nomes de países (em português, conforme postosData.ts)
 * para códigos ISO 3166-1 alpha-2 usados pela lib flag-icons.
 */
export const COUNTRY_TO_FLAG_CODE: Record<string, string> = {
  // África
  'Costa do Marfim': 'ci',
  'Nigéria': 'ng',
  'Gana': 'gh',
  'Etiópia': 'et',
  'Argélia': 'dz',
  'Mali': 'ml',
  'Guiné Bissau': 'gw',
  'Congo': 'cg',
  'Egito': 'eg',
  'Sudão': 'sd',
  'África do Sul': 'za',
  'Guiné': 'gn',
  'Benin': 'bj',
  'Senegal': 'sn',
  'Tanzânia': 'tz',
  'Botsuana': 'bw',
  'Zimbábue': 'zw',
  'Camarões': 'cm',
  'Ruanda': 'rw',
  'Rep. Dem. do Congo': 'cd',
  'Gabão': 'ga',
  'Togo': 'tg',
  'Angola': 'ao',
  'Zâmbia': 'zm',
  'Guiné Equatorial': 'gq',
  'Moçambique': 'mz',
  'Quênia': 'ke',
  'Mauritânia': 'mr',
  'Cabo Verde': 'cv',
  'Marrocos': 'ma',
  'São Tomé e Príncipe': 'st',
  'Tunísia': 'tn',
  'Burkina Faso': 'bf',
  'Namíbia': 'na',

  // América Central e Caribe
  'Belize': 'bz',
  'Barbados': 'bb',
  'Santa Lúcia': 'lc',
  'Guatemala': 'gt',
  'Cuba': 'cu',
  'Jamaica': 'jm',
  'São Vicente e Granadinas': 'vc',
  'Nicarágua': 'ni',
  'Bahamas': 'bs',
  'Panamá': 'pa',
  'Trinidad e Tobago': 'tt',
  'Haiti': 'ht',
  'República Dominicana': 'do',
  'Costa Rica': 'cr',
  'El Salvador': 'sv',
  'Honduras': 'hn',

  // América do Norte
  'EUA': 'us',
  'Canadá': 'ca',
  'México': 'mx',

  // América do Sul
  'Uruguai': 'uy',
  'Paraguai': 'py',
  'Colômbia': 'co',
  'Argentina': 'ar',
  'Venezuela': 've',
  'Bolívia': 'bo',
  'Guiana': 'gy',
  'Peru': 'pe',
  'Equador': 'ec',
  'Chile': 'cl',
  'Suriname': 'sr',
  'Guiana Francesa': 'gf',

  // Ásia e Oriente Médio
  'Emirados Árabes Unidos': 'ae',
  'Jordânia': 'jo',
  'Cazaquistão': 'kz',
  'Iraque': 'iq',
  'Tailândia': 'th',
  'Líbano': 'lb',
  'Palestina': 'ps',
  'China': 'cn',
  'Sri Lanka': 'lk',
  'Bangladesh': 'bd',
  'Síria': 'sy',
  'Catar': 'qa',
  'Timor Leste': 'tl',
  'Japão': 'jp',
  'Vietnã': 'vn',
  'Hong Kong': 'hk',
  'Paquistão': 'pk',
  'Indonésia': 'id',
  'Nepal': 'np',
  'Malásia': 'my',
  'Kuwait': 'kw',
  'Barém': 'bh',
  'Filipinas': 'ph',
  'Omã': 'om',
  'Índia': 'in',
  'Coreia do Norte': 'kp',
  'Arábia Saudita': 'sa',
  'Coreia do Sul': 'kr',
  'Singapura': 'sg',
  'Taiwan': 'tw',
  'Irã': 'ir',
  'Israel': 'il',
  'Myanmar': 'mm',
  'Camboja': 'kh',

  // Europa
  'Países Baixos': 'nl',
  'Turquia': 'tr',
  'Grécia': 'gr',
  'Azerbaijão': 'az',
  'Espanha': 'es',
  'Sérvia': 'rs',
  'Alemanha': 'de',
  'Suíça': 'ch',
  'Eslováquia': 'sk',
  'Bélgica': 'be',
  'Romênia': 'ro',
  'Hungria': 'hu',
  'França': 'fr',
  'Dinamarca': 'dk',
  'Irlanda': 'ie',
  'Reino Unido': 'gb',
  'Suécia': 'se',
  'Portugal': 'pt',
  'Armênia': 'am',
  'Ucrânia': 'ua',
  'Eslovênia': 'si',
  'Finlândia': 'fi',
  'Belarus': 'by',
  'Rússia': 'ru',
  'Chipre': 'cy',
  'Noruega': 'no',
  'Itália': 'it',
  'Bósnia-Herzegovina': 'ba',
  'Bulgária': 'bg',
  'Estônia': 'ee',
  'Geórgia': 'ge',
  'Albânia': 'al',
  'Polônia': 'pl',
  'Vaticano': 'va',
  'Áustria': 'at',
  'Croácia': 'hr',
  'Rep. Tcheca': 'cz',

  // Oceania
  'Austrália': 'au',
  'Nova Zelândia': 'nz',
};

export function getFlagCode(country: string): string | null {
  return COUNTRY_TO_FLAG_CODE[country] || null;
}
